apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config
  namespace: argo-rollouts
data:
  trafficRouterPlugins: |-
    - name: "sgsgbaek/goplugintest"
      location: "https://github.com/sgsgbaek/goplugintest/releases/download/v1.1.0/gateway-api-plugin-linux-amd64"
      args:
        - "--log-level"
        - "debug"